### ISSUE TITLE
'generic_logsumexp' not defined when running code sample

### ISSUE THREAD

**Issue by cvignac** [jeanfeydy/geomloss#17]
Hello Jean,
the library looks really nice, thank you for your work!

Unfortunately, I don't manage to run the code sample in the index page. I get the following error:
```
line 73, in keops_lse
    log_conv = generic_logsumexp("( B - (P * " + cost + " ) )",
NameError: name 'generic_logsumexp' is not defined
```
It happens every time I try to use the multiscale Sinkhorn. However, tensorized versions of Sinkhorn seem to work well, both on CPU and GPU. Has this issue been referenced before?

Thanks

**Comment by jeanfeydy** [comment]
Hi @cvignac ,

Thanks for your feedback!
In all likelihood, this will be fixed by installing the [KeOps](http://www.kernel-operations.io/keops/python/installation.html) library. As discussed in the [getting started](https://www.kernel-operations.io/geomloss/api/install.html) guide, it is a hard dependency for the `"online"` and `"multiscale"` backends of `SamplesLoss`.

Best regards,
Jean

**Comment by cvignac** [comment]
I had indeed missed that step, thank you!
